stages:
  - build
  - test
# Linux builds
build_linux_gcc:
  stage: build
  tags:
    - x86
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential curl autoconf automake libtool 
  script:
    - gcc --version
    - autoreconf -if
    - ./configure
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - libovvc/.libs/libovvc.so.0.0.3
      - libovvc/.libs/libovvc.so.0
      - examples/.libs/dectest
      - examples/dectest

AllIntra_CTC_gcc:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc
  before_script:
    - apt update && apt install -y curl
  script:
    - ./CI/checkMD5.sh ./CI/test_bitstreams/all_intra ./examples/dectest http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/all_intra/

LowDelay_CTC_gcc:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc
  before_script:
    - apt update && apt install -y curl
  script:
    - ./CI/checkMD5.sh ./CI/test_bitstreams/low_delay ./examples/dectest http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/low_delay/

RandomAccess_CTC_gcc:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc
  before_script:
    - apt update && apt install -y curl
  script:
    - ./CI/checkMD5.sh ./CI/test_bitstreams/random_access ./examples/dectest http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/random_access/