stages:
  - build
  - test
# Linux builds
build_linux_gcc_debug:
  stage: build
  tags:
    - x86
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential curl
  script:
    - gcc --version
    - ./configure --cc=gcc --debug --build-dir=debug
    - cd debug
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

build_linux_gcc_release:
  stage: build
  tags:
    - x86
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential curl
  script:
    - gcc --version
    - ./configure --cc=gcc --release --build-dir=release
    - cd release
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - release/libovvc.a
      - release/libovvc.so
      - release/examples/dectest

AllIntra_CTC_gcc_release:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc_release
  before_script:
    - apt update && apt install -y build-essential curl
  script:
    - ./configure --release --build-dir=release --teststreams-url=http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/all_intra/
    - cd release
    - make test

LowDelay_CTC_gcc_release:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc_release
  before_script:
    - apt update && apt install -y build-essential curl
  script:
    - ./configure --release --build-dir=release --teststreams-url=http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/low_delay/
    - cd release
    - make test

RandomAccess_CTC_gcc_release:
  stage: test
  tags:
    - x86
  image: ubuntu
  dependencies:
    - build_linux_gcc_release
  before_script:
    - apt update && apt install -y build-essential curl
  script:
    - ./configure --release --build-dir=release --teststreams-url=http://openvvc.insa-rennes.fr/bitstreams/JVET_CTC/random_access/
    - cd release
    - make test
