stages:
  - build
  - test
# Linux builds
build_linux_gcc_debug:
  stage: build
  image: gcc
  script:
    - gcc --version
    - ./configure --cc=gcc --debug --build-dir=debug
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

non_reg_gcc_debug:
  stage: test
  image: ubuntu
  dependencies:
    - build_linux_gcc_debug
  script:
    - ./CI/checkMD5.sh CI/test_bitstreams/ ./debug/examples/dectest

build_linux_clang_debug:
  stage: build
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential clang
  script:
    - clang --version
    - ./configure --cc=clang --debug --build-dir=debug
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

non_reg_clang_debug:
  stage: test
  image: ubuntu
  dependencies:
    - build_linux_clang_debug
  script:
    - ./CI/checkMD5.sh CI/test_bitstreams/ ./debug/examples/dectest

build_linux_gcc_release:
  stage: build
  image: gcc
  allow_failure: true
  script:
    - gcc --version
    - ./configure --cc=gcc --release --build-dir=release
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - release/libovvc.a
      - release/libovvc.so
      - release/examples/dectest

build_arm_linux_gcc_release:
  stage: build
  tags:
    - ARM
  allow_failure: true
  script:
    - gcc --version
    - ./configure --cc=gcc --release --build-dir=release
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - release/libovvc.a
      - release/libovvc.so
      - release/examples/dectest

build_arm_linux_gcc_debug:
  stage: build
  tags:
    - ARM
  script:
    - gcc --version
    - ./configure --cc=gcc --debug --build-dir=debug
    - make
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

arm_non_reg_gcc_debug:
  stage: test
  tags:
    - ARM
  dependencies:
    - build_arm_linux_gcc_debug
  script:
    - ./CI/checkMD5.sh CI/test_bitstreams/ ./debug/examples/dectest
