stages:
  - build
  - test
# Linux builds
build_linux_gcc_debug:
  stage: build
  image: gcc
  script:
    - gcc --version
    - ./configure gcc
    - make BUILD_TYPE=DEBUG
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

non_reg_gcc_debug:
  stage: test
  image: ubuntu
  dependencies:
    - build_linux_gcc_debug
  script:
    - ./CI/checkMD5.sh CI ./debug/examples/dectest

build_linux_clang_debug:
  stage: build
  image: ubuntu
  before_script:
    - apt update && apt install -y build-essential clang
  script:
    - clang --version
    - ./configure clang
    - make BUILD_TYPE=DEBUG
# Files to keep after compilation
  artifacts:
    paths:
      - debug/libovvc.a
      - debug/libovvc.so
      - debug/examples/dectest

non_reg_clang_debug:
  stage: test
  image: ubuntu
  dependencies:
    - build_linux_clang_debug
  script:
    - ./CI/checkMD5.sh CI ./debug/examples/dectest

build_linux_gcc_release:
  stage: build
  image: gcc
  allow_failure: true
  script:
    - gcc --version
    - ./configure gcc
    - make BUILD_TYPE=RELEASE
# Files to keep after compilation
  artifacts:
    paths:
      - release/libovvc.a
      - release/libovvc.so
      - release/examples/dectest
