language: c

os:
  - linux
  - osx
  # - windows

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export MAKE=mingw32-make; else export MAKE=make; fi
  - ./configure -cc=$TRAVIS_COMPILER
  - $MAKE
  - $MAKE test
